steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "ssh", "apitest", "--zone=southamerica-east1-b", "--command='exit ; ls'"]
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
