steps:
- name: "gcr.io/cloud-builders/gcloud"
  entrypoint : bin/sh
  args: ["compute", "ssh", "emeierd92@apitest", "--zone=southamerica-east1-b", "--command='ls testgitgcp/technical-discussion/'"]
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
