steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["compute", "ssh", "emeierd92@apitest", "--zone=southamerica-east1-b", "--command='git -C testgitgcp/technical-discussion/ pull'"]
timeout: "1600s"
options:
 logging: CLOUD_LOGGING_ONLY
